name: Check for schema update

on:
  repository_dispatch:
    types: update-schema
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: {} # Allow manually kicking off builds

jobs:
  check_for_update:
    name: Check for schema update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 1

    - name: Set up Node 14
      uses: actions/setup-node@v4
      with:
        node-version: 14.x

    - name: Cache npm packages
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('tools/update-schema/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install npm packages
      working-directory: ./tools/update-schema
      run: npm install

    - name: Run update-schema tool
      working-directory: ./tools/update-schema
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.SCHEMABOT_ACCESS_TOKEN }}
        REPO_WORKING_DIRECTORY: ./../../
        GIT_NAME: schemabot
        GIT_EMAIL: durov2005@gmail.com
        NODE_NO_WARNINGS: "1"
      run: node index
